In [1]:
import torch
import numpy as np

In [2]:
if torch.cuda.is_available():
  device = torch.device("cuda")
  x = torch.ones(5, device=device)
  print(x)

tensor([1., 1., 1., 1., 1.], device='cuda:0')


In [4]:
if torch.cuda.is_available():
  device = torch.device("cuda")
  x = torch.ones(5, device=device)
  print(x)
  x = x.to("cpu")
  print(x)
  z = x.numpy()
  print(z)

tensor([1., 1., 1., 1., 1.], device='cuda:0')
tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
