In [1]:
import torch
import numpy as np

In [14]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [15]:
a_np = np.array([0.5,0.4,2])
print(a_np)

[0.5 0.4 2. ]


In [16]:
b_tensor = torch.tensor(a_np)
print(b_tensor)

tensor([0.5000, 0.4000, 2.0000], dtype=torch.float64)


In [17]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [18]:
print(type(b))
print(type(a))

<class 'numpy.ndarray'>
<class 'torch.Tensor'>


In [21]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    x =  torch.ones(5, device= device)
    print(x)
    #z = x.numpy()
    #print(z)

tensor([1., 1., 1., 1., 1.], device='cuda:0')


In [23]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    x =  torch.ones(5, device= device)
    print(x)
    x = x.to("cpu")
    print(x)
    z = x.numpy()
    print(z)

tensor([1., 1., 1., 1., 1.], device='cuda:0')
tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
